name = "khmerlibrary"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "khmerlibrary-db"
database_id = "replace_with_cloudflare_d1_database_id"

[[r2_buckets]]
binding = "BOOKS_BUCKET"
bucket_name = "story"
